### ISSUE TITLE
script variable: entity facing angle

### ISSUE THREAD

**Issue by minotalen** [moddio/moddio2#655]
https://www.modd.io/docs/variables/unitsFacingAngle
https://moddio.nolt.io/280

**Comment by bruh-9000** [comment]
https://github.com/moddio/moddio2/compare/master...bruh-9000:moddio2:patch-1

I believe this would work, but I can't test it right now. I'll look into it more tonight.

**Comment by bruh-9000** [comment]
https://github.com/moddio/moddio2/pull/667
